/mnt/c/Users/sermo/DjangoTFG/pruebaNextflow/work/9e/6ab6dc44bb970cb955979ae37b7532/.command.sh: line 2: get_inference: command not found
